ARCH=Linux
include make_$(ARCH)

#Enter executable name here:
EXEC=poisson

#Enter Modules here:
MOD = pardat.o ./output.o

#Enter objects here:
OBJ = ./red_black.o

#External objects:
EXTOBJ=ErrHnd.o types.o boundary_functions.o

#Don't remove:
include Make.rul
